runtime:  custom
env: flex
env_variables: 
  BBDD_ROOT_PASSWORD: "d2VWZkjgYDdaPJu"
  BBDD_DATABASE: "funnycheapp"
  BBDD_USER: "funnycheapp"
  BBDD_PASSWORD: "d2VWZkjgYDdaPJu"
  BBDD_HOST: "funnycheap.cbniafc7cbgi.us-east-2.rds.amazonaws.com"
  BBDD_PORT: 5432
  SQLALCHEMY_TRACK_MODIFICATIONS: True

