name: Push to GCR GitHub Action
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-push-to-gcr:
    name: "Bulding and pushing images"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Building and pushing the image"
        uses: ./
        with:
          gcloud_service_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          registry: gcr.io
          project_id: ${{ secrets.PROYECT_ID }}
          image_name: funcheap
          image_tag: funcheap-${{ github.sha }}, ${{ github.sha }}
          dockerfile: Dockerfile
          target: build